### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by PentagramTr**

### CODE REVIEW

**Comment by sienori** [comment]
Thank you!
Sorry to trouble you, please post a translation in Crowdin.
https://crowdin.com/project/simple-translate
I will apply the posted translation on release of the new version.

**Comment by PentagramTr** [comment]
@sienori 

Someone else has already translated them.What should I do now?I don't know how to use this site.

<details><summary>Screenshot:</summary>

screenshot-crowdin com-2019 02 11-21-31-25


</details>

**Comment by sienori** [comment]
There is no need to do anything for already translated strings.
I would appreciate it if you could translate strings that has not been translated to anyone yet.
(A red icon is displayed for untranslated strings)

**Comment by PentagramTr** [comment]
Done.
I also corrected some wrong translations.
Thnak you.
@sienori

**Pull request closed without merging**
